name: .NET Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.*'
      
    - name: Restore dependencies
      run: dotnet restore TrackingApi.sln
    
    - name: Build
      run: dotnet build TrackingApi.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test TrackingApi.sln --configuration Release --no-build --verbosity normal